### ISSUE TITLE
Scrape search results?

### ISSUE THREAD

**Issue by YAMLcase** [iulspop/slack-web-scraper#14]
Can this scrape from the search results page?  for instance, I'd like to search for all messages I've sent over the past year.

**Comment by iulspop** [comment]
Currently, the scraping script can only be configured to scrape a channel or DM. I supposed an additional script can be written to scrape search results for a given search string. I'm not sure how easily the existing code can be reused for writing that script, since the search results page may be significantly different from a channel feed.

I'm happy to help you write this feature and accept your contribution.
